//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectricEase.Data.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account_Master
    {
        public int Client_ID { get; set; }
        public string User_ID { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Phone { get; set; }
        public string UserColor { get; set; }
        public byte[] Photo { get; set; }
        public string E_Mail { get; set; }
        public string Password { get; set; }
        public bool Site_Administrator { get; set; }
        public bool Account_Administrator { get; set; }
        public bool Job_Administrator { get; set; }
        public bool Part_Administrator { get; set; }
        public bool Labor_Administrator { get; set; }
        public bool Legal_Adminstrator { get; set; }
        public bool Assembly_Administrator { get; set; }
        public bool Job_Description_Report { get; set; }
        public bool Client_Estimation_Report { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public bool CreatedBy_SuperUser { get; set; }
        public string Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> Subscribe { get; set; }
        public Nullable<bool> IsFirst { get; set; }
    }
}
