//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectricEase.Data.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assemblies_Labor
    {
        public int Client_Id { get; set; }
        public string Assemblies_Name { get; set; }
        public int Labour_ID { get; set; }
        public string Laborer_Name { get; set; }
        public string Laborer_Phone { get; set; }
        public byte[] Laborer_Photo { get; set; }
        public Nullable<decimal> Lobor_Cost { get; set; }
        public Nullable<decimal> Burden { get; set; }
        public Nullable<decimal> Lobor_Resale { get; set; }
        public Nullable<decimal> Estimated_Hour { get; set; }
        public Nullable<decimal> Actual_Hours { get; set; }
        public Nullable<decimal> Expected_Total { get; set; }
        public Nullable<decimal> Estimated_Total { get; set; }
        public Nullable<decimal> Actual_Total { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
