//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectricEase.Data.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_Master
    {
        public Client_Master()
        {
            this.TimeSheet_Master = new HashSet<TimeSheet_Master>();
        }
    
        public int Client_ID { get; set; }
        public string Client_Company { get; set; }
        public byte[] Client_Logo { get; set; }
        public string Address { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Contact_person { get; set; }
        public string Sender_EmailAddress { get; set; }
        public string Sender_EmailPassword { get; set; }
        public string DomainName { get; set; }
        public Nullable<int> SMTP_Port { get; set; }
        public string SMTP_Host { get; set; }
        public string JobIDPreffix { get; set; }
        public Nullable<int> AutoSaveTime_InSecs { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> Distributor_ID { get; set; }
    
        public virtual ICollection<TimeSheet_Master> TimeSheet_Master { get; set; }
    }
}
