//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectricEase.Data.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distributor_Assemblies_Master
    {
        public Distributor_Assemblies_Master()
        {
            this.Distributor_Assemblies_Parts = new HashSet<Distributor_Assemblies_Parts>();
        }
    
        public int Distributor_Id { get; set; }
        public string Assemblies_Name { get; set; }
        public string Assemblies_Category { get; set; }
        public string Assemblies_Description { get; set; }
        public string severity { get; set; }
        public decimal labor_cost { get; set; }
        public decimal labor_ResaleCost { get; set; }
        public decimal labor_EstimatedHours { get; set; }
        public decimal Labor_EstimatedCostTotal { get; set; }
        public decimal Lobor_EstimatedResaleTotal { get; set; }
        public decimal Parts_EstimatedCostTotal { get; set; }
        public decimal Parts_EstimatedResaleTotal { get; set; }
        public decimal Estimated_Qty_Total { get; set; }
        public decimal Grand_EstCost_Total { get; set; }
        public decimal Grand_EstResale_Total { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public Nullable<bool> Isactive { get; set; }
        public string Type { get; set; }
        public int AssemblyID { get; set; }
    
        public virtual Distributor_Master Distributor_Master { get; set; }
        public virtual ICollection<Distributor_Assemblies_Parts> Distributor_Assemblies_Parts { get; set; }
    }
}
