//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectricEase.Data.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distributor_Master
    {
        public Distributor_Master()
        {
            this.Distributor_Assemblies_Master = new HashSet<Distributor_Assemblies_Master>();
            this.Distributor_Assemblies_Parts = new HashSet<Distributor_Assemblies_Parts>();
            this.Distributor_Parts_Details = new HashSet<Distributor_Parts_Details>();
        }
    
        public int ID { get; set; }
        public string Company { get; set; }
        public int No_Of_Users { get; set; }
        public string Company_Url { get; set; }
        public Nullable<System.DateTime> Expiry_Date { get; set; }
        public string Email { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CompanyLogo { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
    
        public virtual ICollection<Distributor_Assemblies_Master> Distributor_Assemblies_Master { get; set; }
        public virtual ICollection<Distributor_Assemblies_Parts> Distributor_Assemblies_Parts { get; set; }
        public virtual ICollection<Distributor_Parts_Details> Distributor_Parts_Details { get; set; }
    }
}
