//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectricEase.Data.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distributor_Assemblies_Parts
    {
        public int Distributor_ID { get; set; }
        public string Assemblies_Name { get; set; }
        public string Assemblies_Category { get; set; }
        public int Part_ID { get; set; }
        public string Part_Number { get; set; }
        public string Part_Category { get; set; }
        public decimal Part_Cost { get; set; }
        public byte[] Parts_Photo { get; set; }
        public decimal Part_Resale { get; set; }
        public decimal Estimated_Qty { get; set; }
        public Nullable<decimal> Actual_Qty { get; set; }
        public Nullable<decimal> Expected_Total { get; set; }
        public Nullable<decimal> Estimated_Total { get; set; }
        public decimal EstimatedCost_Total { get; set; }
        public decimal EstimatedResale_Total { get; set; }
        public Nullable<decimal> Actual_Total { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> LaborUnit { get; set; }
        public int AssemblyID { get; set; }
    
        public virtual Distributor_Assemblies_Master Distributor_Assemblies_Master { get; set; }
        public virtual Distributor_Master Distributor_Master { get; set; }
    }
}
