//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectricEase.Data.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class ElectricEaseEntitiesContext : DbContext
    {
        public ElectricEaseEntitiesContext()
            : base("name=ElectricEaseEntitiesContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Account_Master> Account_Master { get; set; }
        public DbSet<Assemblies_Labor> Assemblies_Labor { get; set; }
        public DbSet<Assemblies_Master> Assemblies_Master { get; set; }
        public DbSet<Assemblies_Parts> Assemblies_Parts { get; set; }
        public DbSet<Client_Master> Client_Master { get; set; }
        public DbSet<Distributor_Assemblies_Master> Distributor_Assemblies_Master { get; set; }
        public DbSet<Distributor_Assemblies_Parts> Distributor_Assemblies_Parts { get; set; }
        public DbSet<Distributor_Master> Distributor_Master { get; set; }
        public DbSet<Distributor_Parts_Details> Distributor_Parts_Details { get; set; }
        public DbSet<Job_AssembliesDetails> Job_AssembliesDetails { get; set; }
        public DbSet<Job_Assembly_Labor> Job_Assembly_Labor { get; set; }
        public DbSet<Job_Assembly_Parts> Job_Assembly_Parts { get; set; }
        public DbSet<Job_Attachments> Job_Attachments { get; set; }
        public DbSet<Job_Calendar> Job_Calendar { get; set; }
        public DbSet<Job_DJE_VQ_Details> Job_DJE_VQ_Details { get; set; }
        public DbSet<Job_EstimationDetails> Job_EstimationDetails { get; set; }
        public DbSet<Job_Labor> Job_Labor { get; set; }
        public DbSet<Job_Legal> Job_Legal { get; set; }
        public DbSet<Job_Master> Job_Master { get; set; }
        public DbSet<Job_Parts> Job_Parts { get; set; }
        public DbSet<Labor_Details> Labor_Details { get; set; }
        public DbSet<Legal_Details> Legal_Details { get; set; }
        public DbSet<Parts_Audit> Parts_Audit { get; set; }
        public DbSet<Parts_Details> Parts_Details { get; set; }
        public DbSet<Sow_Master> Sow_Master { get; set; }
        public DbSet<Super_Admin_Assemblies_Master> Super_Admin_Assemblies_Master { get; set; }
        public DbSet<Super_Admin_Assemblies_Parts> Super_Admin_Assemblies_Parts { get; set; }
        public DbSet<Super_Admin_Parts_Details> Super_Admin_Parts_Details { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<TimeSheet_Details> TimeSheet_Details { get; set; }
        public DbSet<TimeSheet_Log> TimeSheet_Log { get; set; }
        public DbSet<TimeSheet_Master> TimeSheet_Master { get; set; }
        public DbSet<ImportPart> ImportParts { get; set; }
    
        public virtual int EE_ExportPartsInJob(Nullable<int> jobID)
        {
            var jobIDParameter = jobID.HasValue ?
                new ObjectParameter("JobID", jobID) :
                new ObjectParameter("JobID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EE_ExportPartsInJob", jobIDParameter);
        }
    
        public virtual ObjectResult<EE_GetAllDistributorPartsDetailList_Result> EE_GetAllDistributorPartsDetailList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EE_GetAllDistributorPartsDetailList_Result>("EE_GetAllDistributorPartsDetailList");
        }
    
        public virtual ObjectResult<EE_GetAllPartsDetailList_Result> EE_GetAllPartsDetailList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EE_GetAllPartsDetailList_Result>("EE_GetAllPartsDetailList");
        }
    
        public virtual ObjectResult<EE_GetAllUsersList_Result> EE_GetAllUsersList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EE_GetAllUsersList_Result>("EE_GetAllUsersList");
        }
    
        public virtual int EE_GetAssembliesJobParts(Nullable<int> jobID)
        {
            var jobIDParameter = jobID.HasValue ?
                new ObjectParameter("JobID", jobID) :
                new ObjectParameter("JobID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EE_GetAssembliesJobParts", jobIDParameter);
        }
    
        public virtual ObjectResult<EE_GetAssembliesList_Result> EE_GetAssembliesList(Nullable<int> clientID)
        {
            var clientIDParameter = clientID.HasValue ?
                new ObjectParameter("ClientID", clientID) :
                new ObjectParameter("ClientID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EE_GetAssembliesList_Result>("EE_GetAssembliesList", clientIDParameter);
        }
    
        public virtual ObjectResult<byte[]> EE_GetClient(Nullable<int> clientid)
        {
            var clientidParameter = clientid.HasValue ?
                new ObjectParameter("clientid", clientid) :
                new ObjectParameter("clientid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<byte[]>("EE_GetClient", clientidParameter);
        }
    
        public virtual ObjectResult<EE_GetDistributorAssembliesGrid_Result> EE_GetDistributorAssembliesGrid()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EE_GetDistributorAssembliesGrid_Result>("EE_GetDistributorAssembliesGrid");
        }
    
        public virtual int EE_GetDistributorAssembliesList(string searchStr, string sortBy, string sortDir, string skip, string take, ObjectParameter filteredResultsCount, ObjectParameter totalResultsCount, string category)
        {
            var searchStrParameter = searchStr != null ?
                new ObjectParameter("searchStr", searchStr) :
                new ObjectParameter("searchStr", typeof(string));
    
            var sortByParameter = sortBy != null ?
                new ObjectParameter("sortBy", sortBy) :
                new ObjectParameter("sortBy", typeof(string));
    
            var sortDirParameter = sortDir != null ?
                new ObjectParameter("sortDir", sortDir) :
                new ObjectParameter("sortDir", typeof(string));
    
            var skipParameter = skip != null ?
                new ObjectParameter("Skip", skip) :
                new ObjectParameter("Skip", typeof(string));
    
            var takeParameter = take != null ?
                new ObjectParameter("Take", take) :
                new ObjectParameter("Take", typeof(string));
    
            var categoryParameter = category != null ?
                new ObjectParameter("Category", category) :
                new ObjectParameter("Category", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EE_GetDistributorAssembliesList", searchStrParameter, sortByParameter, sortDirParameter, skipParameter, takeParameter, filteredResultsCount, totalResultsCount, categoryParameter);
        }
    
        public virtual ObjectResult<EE_GetDistributorExpAssembliesList_Result> EE_GetDistributorExpAssembliesList(Nullable<int> distributor_ID)
        {
            var distributor_IDParameter = distributor_ID.HasValue ?
                new ObjectParameter("Distributor_ID", distributor_ID) :
                new ObjectParameter("Distributor_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EE_GetDistributorExpAssembliesList_Result>("EE_GetDistributorExpAssembliesList", distributor_IDParameter);
        }
    
        public virtual ObjectResult<EE_GetJobAssembliesDetailList_Result> EE_GetJobAssembliesDetailList(Nullable<int> clientID, string assembliesName)
        {
            var clientIDParameter = clientID.HasValue ?
                new ObjectParameter("ClientID", clientID) :
                new ObjectParameter("ClientID", typeof(int));
    
            var assembliesNameParameter = assembliesName != null ?
                new ObjectParameter("AssembliesName", assembliesName) :
                new ObjectParameter("AssembliesName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EE_GetJobAssembliesDetailList_Result>("EE_GetJobAssembliesDetailList", clientIDParameter, assembliesNameParameter);
        }
    
        public virtual ObjectResult<EE_GetJobAssembliesLaborDetailList_Result> EE_GetJobAssembliesLaborDetailList(Nullable<int> client_ID, string assemblies_Name)
        {
            var client_IDParameter = client_ID.HasValue ?
                new ObjectParameter("Client_ID", client_ID) :
                new ObjectParameter("Client_ID", typeof(int));
    
            var assemblies_NameParameter = assemblies_Name != null ?
                new ObjectParameter("Assemblies_Name", assemblies_Name) :
                new ObjectParameter("Assemblies_Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EE_GetJobAssembliesLaborDetailList_Result>("EE_GetJobAssembliesLaborDetailList", client_IDParameter, assemblies_NameParameter);
        }
    
        public virtual ObjectResult<EE_GetJobCalenderList_Result> EE_GetJobCalenderList(Nullable<int> clientID, Nullable<int> jobID)
        {
            var clientIDParameter = clientID.HasValue ?
                new ObjectParameter("ClientID", clientID) :
                new ObjectParameter("ClientID", typeof(int));
    
            var jobIDParameter = jobID.HasValue ?
                new ObjectParameter("JobID", jobID) :
                new ObjectParameter("JobID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EE_GetJobCalenderList_Result>("EE_GetJobCalenderList", clientIDParameter, jobIDParameter);
        }
    
        public virtual ObjectResult<EE_GetJobDetailList_Result> EE_GetJobDetailList(Nullable<int> clientID)
        {
            var clientIDParameter = clientID.HasValue ?
                new ObjectParameter("ClientID", clientID) :
                new ObjectParameter("ClientID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EE_GetJobDetailList_Result>("EE_GetJobDetailList", clientIDParameter);
        }
    
        public virtual ObjectResult<EE_GetLabourDetailList_Result> EE_GetLabourDetailList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EE_GetLabourDetailList_Result>("EE_GetLabourDetailList");
        }
    
        public virtual ObjectResult<EE_GetLegalDetailList_Result> EE_GetLegalDetailList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EE_GetLegalDetailList_Result>("EE_GetLegalDetailList");
        }
    
        public virtual ObjectResult<EE_GetMyLabourDetailList_Result> EE_GetMyLabourDetailList(Nullable<int> clientID)
        {
            var clientIDParameter = clientID.HasValue ?
                new ObjectParameter("ClientID", clientID) :
                new ObjectParameter("ClientID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EE_GetMyLabourDetailList_Result>("EE_GetMyLabourDetailList", clientIDParameter);
        }
    
        public virtual ObjectResult<EE_GetMylabourDetails_Result> EE_GetMylabourDetails(Nullable<int> clientID, string laborer_Name)
        {
            var clientIDParameter = clientID.HasValue ?
                new ObjectParameter("ClientID", clientID) :
                new ObjectParameter("ClientID", typeof(int));
    
            var laborer_NameParameter = laborer_Name != null ?
                new ObjectParameter("Laborer_Name", laborer_Name) :
                new ObjectParameter("Laborer_Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EE_GetMylabourDetails_Result>("EE_GetMylabourDetails", clientIDParameter, laborer_NameParameter);
        }
    
        public virtual ObjectResult<EE_GetMyLegalDetailList_Result> EE_GetMyLegalDetailList(Nullable<int> clientID)
        {
            var clientIDParameter = clientID.HasValue ?
                new ObjectParameter("ClientID", clientID) :
                new ObjectParameter("ClientID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EE_GetMyLegalDetailList_Result>("EE_GetMyLegalDetailList", clientIDParameter);
        }
    
        public virtual ObjectResult<EE_GetMyUserList_Result> EE_GetMyUserList(Nullable<int> clientID)
        {
            var clientIDParameter = clientID.HasValue ?
                new ObjectParameter("ClientID", clientID) :
                new ObjectParameter("ClientID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EE_GetMyUserList_Result>("EE_GetMyUserList", clientIDParameter);
        }
    
        public virtual ObjectResult<EE_GetNationWideAllPartsDetailList_Result> EE_GetNationWideAllPartsDetailList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EE_GetNationWideAllPartsDetailList_Result>("EE_GetNationWideAllPartsDetailList");
        }
    
        public virtual ObjectResult<EE_GetNationWideAssembliesGrid_Result> EE_GetNationWideAssembliesGrid()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EE_GetNationWideAssembliesGrid_Result>("EE_GetNationWideAssembliesGrid");
        }
    
        public virtual ObjectResult<EE_GetNationWideAssembliesList_Result> EE_GetNationWideAssembliesList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EE_GetNationWideAssembliesList_Result>("EE_GetNationWideAssembliesList");
        }
    
        public virtual ObjectResult<EE_GetPartsListByClientID_Result> EE_GetPartsListByClientID(Nullable<int> clientID)
        {
            var clientIDParameter = clientID.HasValue ?
                new ObjectParameter("ClientID", clientID) :
                new ObjectParameter("ClientID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EE_GetPartsListByClientID_Result>("EE_GetPartsListByClientID", clientIDParameter);
        }
    
        public virtual ObjectResult<EE_GetSelectedAssembliesLaborerList_Result> EE_GetSelectedAssembliesLaborerList(Nullable<int> clientID, string laborer_Name)
        {
            var clientIDParameter = clientID.HasValue ?
                new ObjectParameter("ClientID", clientID) :
                new ObjectParameter("ClientID", typeof(int));
    
            var laborer_NameParameter = laborer_Name != null ?
                new ObjectParameter("Laborer_Name", laborer_Name) :
                new ObjectParameter("Laborer_Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EE_GetSelectedAssembliesLaborerList_Result>("EE_GetSelectedAssembliesLaborerList", clientIDParameter, laborer_NameParameter);
        }
    
        public virtual ObjectResult<EE_GetSelectedLegalList_Result> EE_GetSelectedLegalList(Nullable<int> clientID, Nullable<int> legalID)
        {
            var clientIDParameter = clientID.HasValue ?
                new ObjectParameter("ClientID", clientID) :
                new ObjectParameter("ClientID", typeof(int));
    
            var legalIDParameter = legalID.HasValue ?
                new ObjectParameter("legalID", legalID) :
                new ObjectParameter("legalID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EE_GetSelectedLegalList_Result>("EE_GetSelectedLegalList", clientIDParameter, legalIDParameter);
        }
    
        public virtual ObjectResult<EE_ImportClientParts_Result> EE_ImportClientParts(string processID, Nullable<int> clientID)
        {
            var processIDParameter = processID != null ?
                new ObjectParameter("ProcessID", processID) :
                new ObjectParameter("ProcessID", typeof(string));
    
            var clientIDParameter = clientID.HasValue ?
                new ObjectParameter("ClientID", clientID) :
                new ObjectParameter("ClientID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EE_ImportClientParts_Result>("EE_ImportClientParts", processIDParameter, clientIDParameter);
        }
    
        public virtual ObjectResult<EE_MyDistributorPartsDetailList_Result> EE_MyDistributorPartsDetailList(Nullable<int> distributor_ID)
        {
            var distributor_IDParameter = distributor_ID.HasValue ?
                new ObjectParameter("Distributor_ID", distributor_ID) :
                new ObjectParameter("Distributor_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EE_MyDistributorPartsDetailList_Result>("EE_MyDistributorPartsDetailList", distributor_IDParameter);
        }
    
        public virtual ObjectResult<EE_MyPartsDetailList_Result> EE_MyPartsDetailList(Nullable<int> clientID)
        {
            var clientIDParameter = clientID.HasValue ?
                new ObjectParameter("ClientID", clientID) :
                new ObjectParameter("ClientID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EE_MyPartsDetailList_Result>("EE_MyPartsDetailList", clientIDParameter);
        }
    
        public virtual int EE_RecalcClientAssembly(string assemblyList, Nullable<int> clientID, string updatedBy)
        {
            var assemblyListParameter = assemblyList != null ?
                new ObjectParameter("AssemblyList", assemblyList) :
                new ObjectParameter("AssemblyList", typeof(string));
    
            var clientIDParameter = clientID.HasValue ?
                new ObjectParameter("ClientID", clientID) :
                new ObjectParameter("ClientID", typeof(int));
    
            var updatedByParameter = updatedBy != null ?
                new ObjectParameter("UpdatedBy", updatedBy) :
                new ObjectParameter("UpdatedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EE_RecalcClientAssembly", assemblyListParameter, clientIDParameter, updatedByParameter);
        }
    
        public virtual int EE_RecalcDistributorAssembly(string assemblyList, Nullable<int> distributorID, string updatedBy)
        {
            var assemblyListParameter = assemblyList != null ?
                new ObjectParameter("AssemblyList", assemblyList) :
                new ObjectParameter("AssemblyList", typeof(string));
    
            var distributorIDParameter = distributorID.HasValue ?
                new ObjectParameter("DistributorID", distributorID) :
                new ObjectParameter("DistributorID", typeof(int));
    
            var updatedByParameter = updatedBy != null ?
                new ObjectParameter("UpdatedBy", updatedBy) :
                new ObjectParameter("UpdatedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EE_RecalcDistributorAssembly", assemblyListParameter, distributorIDParameter, updatedByParameter);
        }
    
        public virtual int EE_RecalcDistributorExportClientAssembly(string assemblyList, string clientIDList, string updatedBy)
        {
            var assemblyListParameter = assemblyList != null ?
                new ObjectParameter("AssemblyList", assemblyList) :
                new ObjectParameter("AssemblyList", typeof(string));
    
            var clientIDListParameter = clientIDList != null ?
                new ObjectParameter("ClientIDList", clientIDList) :
                new ObjectParameter("ClientIDList", typeof(string));
    
            var updatedByParameter = updatedBy != null ?
                new ObjectParameter("UpdatedBy", updatedBy) :
                new ObjectParameter("UpdatedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EE_RecalcDistributorExportClientAssembly", assemblyListParameter, clientIDListParameter, updatedByParameter);
        }
    
        public virtual int EE_RecalcNationalwideExportClientAssembly(string assemblyList, string clientIDList, string updatedBy)
        {
            var assemblyListParameter = assemblyList != null ?
                new ObjectParameter("AssemblyList", assemblyList) :
                new ObjectParameter("AssemblyList", typeof(string));
    
            var clientIDListParameter = clientIDList != null ?
                new ObjectParameter("ClientIDList", clientIDList) :
                new ObjectParameter("ClientIDList", typeof(string));
    
            var updatedByParameter = updatedBy != null ?
                new ObjectParameter("UpdatedBy", updatedBy) :
                new ObjectParameter("UpdatedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EE_RecalcNationalwideExportClientAssembly", assemblyListParameter, clientIDListParameter, updatedByParameter);
        }
    
        public virtual int EE_RecalcNationalwideExportDistributorAssembly(string assemblyList, string distributorIDList, string updatedBy)
        {
            var assemblyListParameter = assemblyList != null ?
                new ObjectParameter("AssemblyList", assemblyList) :
                new ObjectParameter("AssemblyList", typeof(string));
    
            var distributorIDListParameter = distributorIDList != null ?
                new ObjectParameter("DistributorIDList", distributorIDList) :
                new ObjectParameter("DistributorIDList", typeof(string));
    
            var updatedByParameter = updatedBy != null ?
                new ObjectParameter("UpdatedBy", updatedBy) :
                new ObjectParameter("UpdatedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EE_RecalcNationalwideExportDistributorAssembly", assemblyListParameter, distributorIDListParameter, updatedByParameter);
        }
    
        public virtual int EE_RecalcNationwideAssembly(string assemblyList, string updatedBy)
        {
            var assemblyListParameter = assemblyList != null ?
                new ObjectParameter("AssemblyList", assemblyList) :
                new ObjectParameter("AssemblyList", typeof(string));
    
            var updatedByParameter = updatedBy != null ?
                new ObjectParameter("UpdatedBy", updatedBy) :
                new ObjectParameter("UpdatedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EE_RecalcNationwideAssembly", assemblyListParameter, updatedByParameter);
        }
    
        public virtual int EE_ReportParts(Nullable<int> jobid)
        {
            var jobidParameter = jobid.HasValue ?
                new ObjectParameter("Jobid", jobid) :
                new ObjectParameter("Jobid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EE_ReportParts", jobidParameter);
        }
    
        public virtual ObjectResult<EE_SelectedAssembliesPartsDetailList_Result> EE_SelectedAssembliesPartsDetailList(Nullable<int> clientID, string part_Number)
        {
            var clientIDParameter = clientID.HasValue ?
                new ObjectParameter("ClientID", clientID) :
                new ObjectParameter("ClientID", typeof(int));
    
            var part_NumberParameter = part_Number != null ?
                new ObjectParameter("Part_Number", part_Number) :
                new ObjectParameter("Part_Number", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EE_SelectedAssembliesPartsDetailList_Result>("EE_SelectedAssembliesPartsDetailList", clientIDParameter, part_NumberParameter);
        }
    
        public virtual ObjectResult<EE_SelectedAssembliesPartsForJobs_Result> EE_SelectedAssembliesPartsForJobs(Nullable<int> client_ID)
        {
            var client_IDParameter = client_ID.HasValue ?
                new ObjectParameter("Client_ID", client_ID) :
                new ObjectParameter("Client_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EE_SelectedAssembliesPartsForJobs_Result>("EE_SelectedAssembliesPartsForJobs", client_IDParameter);
        }
    
        public virtual ObjectResult<EE_SelectedDistributorAssembliesPartsDetailList_Result> EE_SelectedDistributorAssembliesPartsDetailList(Nullable<int> distributor_ID, string part_Number)
        {
            var distributor_IDParameter = distributor_ID.HasValue ?
                new ObjectParameter("Distributor_ID", distributor_ID) :
                new ObjectParameter("Distributor_ID", typeof(int));
    
            var part_NumberParameter = part_Number != null ?
                new ObjectParameter("Part_Number", part_Number) :
                new ObjectParameter("Part_Number", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EE_SelectedDistributorAssembliesPartsDetailList_Result>("EE_SelectedDistributorAssembliesPartsDetailList", distributor_IDParameter, part_NumberParameter);
        }
    
        public virtual ObjectResult<EE_SelectedNationWideAssembliesPartsDetailList_Result> EE_SelectedNationWideAssembliesPartsDetailList(string part_Number)
        {
            var part_NumberParameter = part_Number != null ?
                new ObjectParameter("Part_Number", part_Number) :
                new ObjectParameter("Part_Number", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EE_SelectedNationWideAssembliesPartsDetailList_Result>("EE_SelectedNationWideAssembliesPartsDetailList", part_NumberParameter);
        }
    
        public virtual int HardDeleteAllUsers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HardDeleteAllUsers");
        }
    
        public virtual int HardDeleteUsers(string userid, Nullable<int> clientid)
        {
            var useridParameter = userid != null ?
                new ObjectParameter("Userid", userid) :
                new ObjectParameter("Userid", typeof(string));
    
            var clientidParameter = clientid.HasValue ?
                new ObjectParameter("Clientid", clientid) :
                new ObjectParameter("Clientid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HardDeleteUsers", useridParameter, clientidParameter);
        }
    
        public virtual ObjectResult<JobReportDetails_Result> JobReportDetails(Nullable<int> clientID)
        {
            var clientIDParameter = clientID.HasValue ?
                new ObjectParameter("ClientID", clientID) :
                new ObjectParameter("ClientID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<JobReportDetails_Result>("JobReportDetails", clientIDParameter);
        }
    
        public virtual int MIGRATE_LABORUNIT_WITHASSEMBLYID(string aSSEMBLY, string cLIENT, string dISTRIBUTOR)
        {
            var aSSEMBLYParameter = aSSEMBLY != null ?
                new ObjectParameter("ASSEMBLY", aSSEMBLY) :
                new ObjectParameter("ASSEMBLY", typeof(string));
    
            var cLIENTParameter = cLIENT != null ?
                new ObjectParameter("CLIENT", cLIENT) :
                new ObjectParameter("CLIENT", typeof(string));
    
            var dISTRIBUTORParameter = dISTRIBUTOR != null ?
                new ObjectParameter("DISTRIBUTOR", dISTRIBUTOR) :
                new ObjectParameter("DISTRIBUTOR", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MIGRATE_LABORUNIT_WITHASSEMBLYID", aSSEMBLYParameter, cLIENTParameter, dISTRIBUTORParameter);
        }
    
        public virtual int MIGRATE_LABORUNIT_WITHASSEMBLYID_FORDISTIRBUTOR(string aSSEMBLY, string cLIENT)
        {
            var aSSEMBLYParameter = aSSEMBLY != null ?
                new ObjectParameter("ASSEMBLY", aSSEMBLY) :
                new ObjectParameter("ASSEMBLY", typeof(string));
    
            var cLIENTParameter = cLIENT != null ?
                new ObjectParameter("CLIENT", cLIENT) :
                new ObjectParameter("CLIENT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MIGRATE_LABORUNIT_WITHASSEMBLYID_FORDISTIRBUTOR", aSSEMBLYParameter, cLIENTParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<USP_TimeSheetDetails_Result> USP_TimeSheetDetails(Nullable<long> timeSheetID, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var timeSheetIDParameter = timeSheetID.HasValue ?
                new ObjectParameter("TimeSheetID", timeSheetID) :
                new ObjectParameter("TimeSheetID", typeof(long));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_TimeSheetDetails_Result>("USP_TimeSheetDetails", timeSheetIDParameter, startDateParameter, endDateParameter);
        }
    }
}
