//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectricEase.Data.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportPart
    {
        public string ProcessID { get; set; }
        public Nullable<int> RowNumber { get; set; }
        public string PartNumber { get; set; }
        public string Category { get; set; }
        public string MyCost { get; set; }
        public string Markup { get; set; }
        public string ResaleCost { get; set; }
        public string LaborUnit { get; set; }
        public string PurchasedFrom { get; set; }
        public string Description { get; set; }
        public string UOM { get; set; }
        public bool Status { get; set; }
        public string Remarks { get; set; }
    }
}
