//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectricEase.Data.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job_Assembly_Labor
    {
        public int Client_Id { get; set; }
        public int Job_ID { get; set; }
        public string Assemblies_Name { get; set; }
        public string Assemblies_Category { get; set; }
        public int AssembliesLabour_ID { get; set; }
        public string Assemblies_Description { get; set; }
        public decimal Lobor_Cost { get; set; }
        public decimal Burden { get; set; }
        public decimal Lobor_Resale { get; set; }
        public decimal Estimated_Hour { get; set; }
        public decimal Actual_Hours { get; set; }
        public Nullable<decimal> Expected_Total { get; set; }
        public Nullable<decimal> Estimated_Total { get; set; }
        public Nullable<decimal> Actual_Total { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
