//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectricEase.Data.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job_Legal
    {
        public int Client_ID { get; set; }
        public int Job_ID { get; set; }
        public int Job_Legal_ID { get; set; }
        public Nullable<int> Legal_ID { get; set; }
        public string Legal_Detail { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
