//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectricEase.Data.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job_AssembliesDetails
    {
        public int Client_Id { get; set; }
        public int Job_ID { get; set; }
        public int JobAssembly_Id { get; set; }
        public string Assemblies_Name { get; set; }
        public string Assemblies_Category { get; set; }
        public Nullable<decimal> Multiplier { get; set; }
        public Nullable<decimal> Est_Qty { get; set; }
        public Nullable<decimal> Est_Cost_Total { get; set; }
        public Nullable<decimal> Est_Resale_Total { get; set; }
        public Nullable<decimal> Act_Qty_Total { get; set; }
        public Nullable<decimal> Actual_Total { get; set; }
        public Nullable<decimal> PartsCostTotal { get; set; }
        public Nullable<decimal> PartsResaleTotal { get; set; }
        public Nullable<decimal> Labor_Cost { get; set; }
        public Nullable<decimal> Labor_Resale { get; set; }
        public Nullable<decimal> Labor_Est_Hours { get; set; }
        public Nullable<decimal> Labor_Est_CostTotal { get; set; }
        public Nullable<decimal> Labor_Est_ResaleTotal { get; set; }
        public Nullable<decimal> Labor_Actual_Total { get; set; }
        public Nullable<decimal> GrandCostTotal { get; set; }
        public Nullable<decimal> GrandResaleTotal { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Updated_By { get; set; }
        public Nullable<bool> Isactive { get; set; }
        public Nullable<decimal> Labor_Actual_Qty { get; set; }
        public string severity { get; set; }
        public decimal GrandActualTotal { get; set; }
        public decimal PartsActualTotal { get; set; }
    }
}
