//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectricEase.Data.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job_DJE_VQ_Details
    {
        public int Status_ID { get; set; }
        public int Client_ID { get; set; }
        public int Job_ID { get; set; }
        public string Expense { get; set; }
        public string Vendor_Name { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> Profit { get; set; }
        public string Job_DJE_VQ_Status { get; set; }
        public Nullable<decimal> Resale_Total { get; set; }
        public Nullable<decimal> Job_DJETotal { get; set; }
        public Nullable<decimal> Job_VQTotal { get; set; }
        public bool IsActive { get; set; }
    }
}
