//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectricEase.Data.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job_Parts
    {
        public int Client_ID { get; set; }
        public int Job_ID { get; set; }
        public int Part_ID { get; set; }
        public string Part_Number { get; set; }
        public decimal Part_Cost { get; set; }
        public byte[] Parts_Photo { get; set; }
        public decimal Part_Resale { get; set; }
        public decimal Estimated_Qty { get; set; }
        public decimal Actual_Qty { get; set; }
        public decimal Expected_Total { get; set; }
        public decimal Estimated_Total { get; set; }
        public decimal Actual_Total { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<decimal> LaborUnit { get; set; }
    }
}
