//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectricEase.Data.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job_Master
    {
        public Job_Master()
        {
            this.TimeSheet_Details = new HashSet<TimeSheet_Details>();
        }
    
        public int Client_Id { get; set; }
        public int Job_ID { get; set; }
        public string Job_Description { get; set; }
        public Nullable<bool> TempPole { get; set; }
        public string Job_AssignedUser { get; set; }
        public string Assemblies_Name { get; set; }
        public string Client_Name { get; set; }
        public string Client_Address { get; set; }
        public string Client_Address2 { get; set; }
        public string Client_City { get; set; }
        public string Client_State { get; set; }
        public string Client_ZipCode { get; set; }
        public string Client_Phone { get; set; }
        public string Client_Mobile { get; set; }
        public string Client_ContactPerson { get; set; }
        public string Client_Fax { get; set; }
        public string Client_Email { get; set; }
        public string Work_Address { get; set; }
        public string Work_Address2 { get; set; }
        public string Work_City { get; set; }
        public string Work_State { get; set; }
        public string Work_Location { get; set; }
        public string Work_ZipCode { get; set; }
        public string Directions_To { get; set; }
        public string Doing_What { get; set; }
        public string Job_Status { get; set; }
        public Nullable<decimal> Parts_GrandExpTotal { get; set; }
        public Nullable<decimal> Parts_GrandEstTotal { get; set; }
        public Nullable<decimal> Parts_GrandActTotal { get; set; }
        public Nullable<decimal> Labor_GrandExpTotal { get; set; }
        public Nullable<decimal> Labor_GrandEstTotal { get; set; }
        public Nullable<decimal> Labor_GrandActTotal { get; set; }
        public Nullable<decimal> Job_Mileage_Estimated { get; set; }
        public Nullable<decimal> Job_Mileage_Actual { get; set; }
        public Nullable<decimal> Job_Mileage_Cost { get; set; }
        public Nullable<decimal> Job_Mileage_ExpTotal { get; set; }
        public Nullable<decimal> Job_Mileage_EstTotal { get; set; }
        public Nullable<decimal> Job_Mileage_ActTotal { get; set; }
        public Nullable<decimal> EstimateValue_SubTotal { get; set; }
        public Nullable<decimal> EstimateValue_Overhead_Percentage { get; set; }
        public Nullable<decimal> EstimateValue_Overhead_EstTotal { get; set; }
        public Nullable<decimal> EstimateValue_Overhead_ExpTotal { get; set; }
        public Nullable<decimal> EstimateValue_Profit_Percentage { get; set; }
        public Nullable<decimal> EstimateValue_Profit_EstTotal { get; set; }
        public Nullable<decimal> EstimateValue_ExpTotal { get; set; }
        public Nullable<decimal> Estimate_Override { get; set; }
        public Nullable<decimal> SalesTax { get; set; }
        public Nullable<decimal> SalesTax_Perc { get; set; }
        public Nullable<decimal> Job_ExpenseTotal { get; set; }
        public Nullable<decimal> Job_EstimatedTotal { get; set; }
        public Nullable<decimal> Job_ActualTotal { get; set; }
        public Nullable<decimal> Profit_Loss_Total { get; set; }
        public Nullable<decimal> Profit_Loss_Perc { get; set; }
        public Nullable<bool> Isactive { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public string JobDisplayId { get; set; }
        public string Job_Number { get; set; }
        public bool IsPriceUpdate { get; set; }
        public System.DateTime PriceUpdatedDate { get; set; }
    
        public virtual ICollection<TimeSheet_Details> TimeSheet_Details { get; set; }
    }
}
