//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectricEase.Data.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job_EstimationDetails
    {
        public int Client_ID { get; set; }
        public int Job_ID { get; set; }
        public int Job_EstimationID { get; set; }
        public Nullable<int> Selected_Estimation_Type { get; set; }
        public Nullable<decimal> Job_AssemblyTotal { get; set; }
        public Nullable<decimal> Estimation1_AssemblyTax { get; set; }
        public Nullable<decimal> Estimation1_AssemblyTotal { get; set; }
        public Nullable<decimal> Estimation2_AssemblyProfit { get; set; }
        public Nullable<decimal> Estimation2_AssemblySubTotal { get; set; }
        public Nullable<decimal> Estimation2_AssemblyTax { get; set; }
        public Nullable<decimal> Estimation2_AssemblyTotal { get; set; }
        public Nullable<decimal> Job_LaborTotal { get; set; }
        public Nullable<decimal> Estimation1_LaborTax { get; set; }
        public Nullable<decimal> Estimation1_laborTotal { get; set; }
        public Nullable<decimal> Estimation2_LaborProft { get; set; }
        public Nullable<decimal> Estimate2_LaborSubTotal { get; set; }
        public Nullable<decimal> Estimate2_LaborTax { get; set; }
        public Nullable<decimal> Estimate2_LaborTotal { get; set; }
        public Nullable<decimal> Job_PartsTotal { get; set; }
        public Nullable<decimal> Estimation1_PartsTax { get; set; }
        public Nullable<decimal> Estimation1_PartsTotal { get; set; }
        public Nullable<decimal> Estimation2_PartsProfit { get; set; }
        public Nullable<decimal> Estimation2_PartsSubTotal { get; set; }
        public Nullable<decimal> Estimation2_PartsTax { get; set; }
        public Nullable<decimal> Estimation2_PartsTotal { get; set; }
        public Nullable<decimal> Job_DJETotal { get; set; }
        public Nullable<decimal> Estimation1_DJETax { get; set; }
        public Nullable<decimal> Estimation1_DJETotal { get; set; }
        public Nullable<decimal> Estimation2_DJEProfit { get; set; }
        public Nullable<decimal> Estimation2_DJESubTotal { get; set; }
        public Nullable<decimal> Estimation2_DJETax { get; set; }
        public Nullable<decimal> Estimation2_DJETotal { get; set; }
        public Nullable<decimal> Job_VQTotal { get; set; }
        public Nullable<decimal> Estimation1_VQTax { get; set; }
        public Nullable<decimal> Estimation1_VQTotal { get; set; }
        public Nullable<decimal> Estimation2_VQProfit { get; set; }
        public Nullable<decimal> Estimation2_VQSubtotal { get; set; }
        public Nullable<decimal> Estimation2_VQTax { get; set; }
        public Nullable<decimal> Estimation2_VQTotal { get; set; }
        public Nullable<decimal> Estimation1_GrandTotal { get; set; }
        public Nullable<decimal> Estimation1_Total { get; set; }
        public Nullable<decimal> Estimation2_GrandTotal { get; set; }
        public Nullable<decimal> Estimation2_SubTotal { get; set; }
        public Nullable<decimal> Estimation2_Total { get; set; }
        public Nullable<decimal> Estimate3_Override { get; set; }
        public Nullable<decimal> Estimate4_Subtotal { get; set; }
        public Nullable<decimal> Estimate4_Tax { get; set; }
        public Nullable<decimal> Estimate4_Total { get; set; }
        public string Estimate4_Data { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public bool IsPriceUpdate { get; set; }
    }
}
