//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectricEase.Data.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Labor_Details
    {
        public int Client_Id { get; set; }
        public string Laborer_Name { get; set; }
        public string Labor_Category { get; set; }
        public string Description { get; set; }
        public string Client_Description { get; set; }
        public decimal Cost { get; set; }
        public Nullable<decimal> Resale_Cost { get; set; }
        public Nullable<decimal> Burden { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Updated_By { get; set; }
        public System.DateTime Updated_Date { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public byte[] Photo { get; set; }
        public Nullable<bool> Gender { get; set; }
        public Nullable<decimal> Rate { get; set; }
    }
}
