//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectricEase.Data.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parts_Audit
    {
        public int AID { get; set; }
        public int Client_ID { get; set; }
        public string Part_Number { get; set; }
        public string Part_Category { get; set; }
        public string Description { get; set; }
        public string Client_Description { get; set; }
        public decimal Cost { get; set; }
        public decimal Resale_Cost { get; set; }
        public string Purchased_From { get; set; }
        public string UOM { get; set; }
        public string Type { get; set; }
        public System.DateTime Created_Date { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public Nullable<int> Distributor_ID { get; set; }
    }
}
