//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectricEase.Data.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Super_Admin_Parts_Details
    {
        public int Client_Id { get; set; }
        public string Part_Number { get; set; }
        public string Part_Category { get; set; }
        public string Description { get; set; }
        public string Client_Description { get; set; }
        public decimal Cost { get; set; }
        public Nullable<decimal> Resale_Cost { get; set; }
        public string Purchased_From { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Updated_By { get; set; }
        public System.DateTime Updated_Date { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string UOM { get; set; }
        public Nullable<decimal> LaborUnit { get; set; }
    }
}
