//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectricEase.Data.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeSheet_Details
    {
        public long DetID { get; set; }
        public Nullable<long> TimeSheetID { get; set; }
        public Nullable<int> Job_ID { get; set; }
        public Nullable<System.DateTime> WorkDate { get; set; }
        public Nullable<decimal> NoOfHours { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string CostCode { get; set; }
    
        public virtual Job_Master Job_Master { get; set; }
        public virtual TimeSheet_Master TimeSheet_Master { get; set; }
    }
}
