//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectricEase.Data.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeSheet_Master
    {
        public TimeSheet_Master()
        {
            this.TimeSheet_Details = new HashSet<TimeSheet_Details>();
            this.TimeSheet_Log = new HashSet<TimeSheet_Log>();
        }
    
        public long TimeSheetID { get; set; }
        public string TimeSheetCode { get; set; }
        public Nullable<int> Client_ID { get; set; }
        public string User_ID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> TotalHours { get; set; }
        public Nullable<decimal> OTHours { get; set; }
        public string Comments { get; set; }
    
        public virtual Client_Master Client_Master { get; set; }
        public virtual ICollection<TimeSheet_Details> TimeSheet_Details { get; set; }
        public virtual ICollection<TimeSheet_Log> TimeSheet_Log { get; set; }
    }
}
